/*
 * This source file was generated by the Gradle 'init' task
 */
package com.team.tetris;

public class App {
    public String getGreeting() {
        return "Hello World! Tetris bootstrapped on Java 17 ✅!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
